# Generated by Django 4.2.4 on 2023-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Estudiante', 'Estudiante'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
