# Generated by Django 4.2.4 on 2023-09-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_dictionary_notification_certificate_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
