# Generated by Django 4.2.4 on 2023-10-03 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_certificate_description_certificate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(blank=True, max_length=500, null=True)),
                ('image2', models.CharField(blank=True, max_length=500, null=True)),
                ('image3', models.CharField(blank=True, max_length=500, null=True)),
                ('image4', models.CharField(blank=True, max_length=500, null=True)),
                ('image5', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning1', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning2', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning3', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning4', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning5', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(blank=True, max_length=500, null=True)),
                ('image2', models.CharField(blank=True, max_length=500, null=True)),
                ('image3', models.CharField(blank=True, max_length=500, null=True)),
                ('image4', models.CharField(blank=True, max_length=500, null=True)),
                ('image5', models.CharField(blank=True, max_length=500, null=True)),
                ('pairimage1', models.CharField(blank=True, max_length=500, null=True)),
                ('pairimage2', models.CharField(blank=True, max_length=500, null=True)),
                ('pairimage3', models.CharField(blank=True, max_length=500, null=True)),
                ('pairimage4', models.CharField(blank=True, max_length=500, null=True)),
                ('pairimage5', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuenceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageReference', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.CharField(blank=True, max_length=500, null=True)),
                ('image2', models.CharField(blank=True, max_length=500, null=True)),
                ('image3', models.CharField(blank=True, max_length=500, null=True)),
                ('image4', models.CharField(blank=True, max_length=500, null=True)),
                ('image5', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='design',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='period',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='num_by_lesson',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='userStudent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='certificateUserStudent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='userTutor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='certificateUserTutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goal',
            name='userStudent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='goalUserStudent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='userTutor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='goalUserTutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='userStudent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='notificationUserStudent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='userTutor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='notificationUserTutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.lesson'),
        ),
        migrations.AddField(
            model_name='userlesson',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraudit',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theoryactivity',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.activity'),
        ),
        migrations.AddField(
            model_name='secuenceactivity',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.activity'),
        ),
        migrations.AddField(
            model_name='recognitionactivity',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.activity'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.notification'),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryactivity',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.activity'),
        ),
        migrations.AddField(
            model_name='medal',
            name='lessonUser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.userlesson'),
        ),
        migrations.AddField(
            model_name='linkactivity',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='App.activity'),
        ),
    ]
